version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_app
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=3000
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=LHU12345
      - DB_NAME=TaiChinhDB
      - JWT_SECRET=HFWfapppadsafdsfsd
      - JWT_REFRESH_SECRET=HFWAFFâsdasdasdasda
      - JWT_EXPIRES_IN=1d
      - LANG=C.UTF-8
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - app-network
    volumes:
      - ./tmp:/usr/src/app/tmp

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      LANG: C.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: 