name: Auto Deploy on tmp Push

on:
  push:
    paths:
      - 'tmp/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.IP_VPS }}
          username: ${{ secrets.VPS_NAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/docker-node-mysql/tmp
            docker-compose down
            docker-compose up -d
