name: Auto Deploy on tmp Push

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: docker_username
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.IP_VPS }}
          username: ${{ secrets.VPS_NAME }}
          key: ${{ secrets.VPS_SSH_KEY }}  # Changed from key_path to key
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/docker-node-mysql
            git pull origin main
            cd tmp
            docker-compose down
            docker-compose up -d
